dist: bionic

language: php

php:
  - 8.1

install:
  - wget https://raw.githubusercontent.com/php-opencv/php-opencv-packages/master/opencv_4.5.5_amd64.deb
  - sudo dpkg -i opencv_4.5.5_amd64.deb
  - phpize
  - ./configure
  - make
  - make install

script:
  - make test

branches:
  only:
    - master